### PR TITLE
Added Markdown blocks,

### PR DESCRIPTION
**Pull request by custa1200**
Added Markdown blocks to be used within Markdown specs to match regular specs.

### CODE REVIEW

**Comment by operatino** [comment]
I'm not sure that `languageRenderers` is the right place for defining the decorators like info/warn and etc. since initially they are done only for code examples. Also, falling back to original MD syntax, everything wrapped in three backticks is code example.

Won't it feel awkward to use code block for non code content? We should think about other options of defining those.

And btw doc/design/spec helpers are actually links, not divs.

**Comment by ndelangen** [comment]
This might be completely insane, but if you're not comfortable with using code-blocks, not too many markdown-blocks remain...

Are you more or less comfortable with something like this:
```
some markdown here

>.source-info
> #section title
>
> this is a paragraph
> 
> 1. list item
> 2. list item

some markdown here
```

This in essence is an extension to the markdown quote block. Along the same lines as code blocks are extended..

**Comment by operatino** [comment]
I've also been thinking about the quote block, I think it fits better here. Code blocks and additional langs should be heavily used for example tech. Also, it was always a really nice addition when SourceJS spec fallback to plain MD nicely, keeping it readable also on GH.

**Comment by custa1200** [comment]
I think the quote works. Would the heading level be rescoped to just inside the block quote? I would assume those headings would not belong in the right hand spec nav either.

**Comment by ndelangen** [comment]
This person asking a question on stackoverflow seems to have had the same idea:
http://stackoverflow.com/questions/1058933/can-i-define-a-class-name-on-paragraph-using-markdown

**Comment by ndelangen** [comment]
If there's some sort of standard out there for doing this, we should consider adopting it instead of inventing our own solution.

I also think we should simply add a class to the block quote, this adds a lot of flexibility. We should not add just a few predetermined options.

**Comment by operatino** [comment]
So I see most of us prefer quotes, so let's think it that direction.

> Would the heading level be rescoped to just inside the block quote?

I would not consider supporting heading in quotes at all, let's keep it simple.

> If there's some sort of standard out there for doing this, we should consider adopting it instead of inventing our own solution.

I'm afraid standard Markdown is quite limited, so anyways we'll need to come up with something own here.

I propose using quotes with some config first line, which could be just a simple word like `info`, `warn`, or let's say a class name with dot in front `.something`, which will allow to be quite flexible, yet without adding lots of complexity.

```
> warn
> Warning message

> info
> Info message

> .custom
> Message block wrapped in `.custom` class name
```

Or we can make a bit more explicit notation, like 

```
> @info
> Info message
```

**Comment by ndelangen** [comment]
Check out this post: 
http://beneb.info/2015/02/more-powerful-markdown-with-custom-renderers/

It's spooky similar to what we do to code blocks. Appears like blockquotes can be extended just the same?

> I would not consider supporting heading in quotes at all, let's keep it simple.

I would, I think it's an important feature to have in this case, especially if this is to be a very generic option where it's a replacement of a div with a class. People expect they can format the stuff inside it, I think.


A period is the universal signifier for a CSS class. I definitely think thats the right marker.
And it's also not something I've seen people do: start a blockquote with a period. Why would anyone start their blockquote with a period?

```
> .source-info
> # Title
>
> The text inside
> ...
```

**Comment by operatino** [comment]
> Check out this post: 
> http://beneb.info/2015/02/more-powerful-markdown-with-custom-renderers/

This MD parser with it's plugins system looks promising indeed https://github.com/markdown-it/markdown-it, we can allow using existing plugins for SourceJS user and bind our plugin system to the thing.

Let's continue with extended blockqoute solution, @custa1200 can you create a new PR with the example implementation? Basically you'll need to parse the text of each blockqoute, and if first line matches the criteria, then you wrap the contents into special markup.

**Comment by ndelangen** [comment]
[markdown-it](https://github.com/markdown-it/markdown-it) would replace [marked](https://github.com/chjj/marked)?

It's plugin system sounds cool. But marked [overriding renderer methods](https://github.com/chjj/marked#overriding-renderer-methods) is also a plugin system of sorts. Is switching markdown renderer worth the hassle?

**Comment by operatino** [comment]
> markdown-it would replace marked?

Potentially yes, but we can start with marked, as it's already used int he core. 

> It's plugin system sounds cool. But marked overriding renderer methods is also a plugin system of sorts. Is switching markdown renderer worth the hassle?

Of course we can make our own system also based on marked, but it's really cool to embrace the plugins from already existing markdown parsing tool. This will allow SourceJS be even more extendable.

**Comment by ndelangen** [comment]
> but it's really cool to embrace the plugins from already existing markdown parsing tool.

I hadn't realized the potential of existing plugins for markdown-it. Does markdown-it have a active community?

**Comment by operatino** [comment]
Not sure how active it is, but there's quite a few plugins.

**Comment by custa1200** [comment]
This looks an interesting implementation. https://github.com/markdown-it/markdown-it-container

**Comment by ndelangen** [comment]
> This looks an interesting implementation. https://github.com/markdown-it/markdown-it-container

Looks great. I vote for replacing marked with markdown-it. 

Do you want to do this @custa1200 ? I'm willing to give it a go as well.

**Comment by custa1200** [comment]
Keen to hear @operatino before jumping into it.

**Comment by operatino** [comment]
markdown-it-container looks nice, but more like an alternative option that user could enable by themselves. In the core, I would preffer sticting to quotes, as we discusses, since these blocks fallbacks really bad:

```
::: .sourcejs-info
Exampmpl info text.
:::
```

on GH looks like

image

**Comment by custa1200** [comment]
I need to get back onto this.

**Comment by operatino** [comment]
So the deal is to use marked modules for now, and add custom blockqoute parsing, that will parse first line:

```
> @warn
> Warning message

> @info
> Info message

> .custom
> Message block wrapped in `.custom` class name
```

On the next stage we'll most likely switch to markdown-it implementation. Switching the lib wont require much work, but skipping this for now will help releasing the MVP faster.

**Pull request closed without merging**
