### PR TITLE
update middleware docs

### PR DESCRIPTION
**Pull request by szarouski**

### CODE REVIEW

**Comment by operatino** [comment]
Huge thank you for the PR! I thought that I updated docs, but seems that I missed that, leaving only some description in docs.

**Comment by operatino** [comment]
BTW, I'm now planning to go deep with React components library support. The idea is to create a SourceJS bundle, as a sub-project, which will allow building easy and scalable React components library out of the box.

@sapegin started to work on React development playground already, which will be a part of this bundle project.

**Comment by szarouski** [comment]
@operatino sounds cool, will it be similar to lego? I also seen video not long time ago about some web application which allows to build and compose react components through web interface. Just can't find it...

**Comment by operatino** [comment]
We have the same demo of constructing any component from SourceJS as lego using UI interface, which is available for some time ago https://www.youtube.com/watch?v=cefy_U5NU4o. But we're not planning to continue it's development.

The project I mentioned is about providing and out of the box SourceJS configuration, allowing to easy build React components documentation.

**Comment by Guria** [comment]
@szarouski did you mean [react ui builder(]http://helmetrex.com/Gallery.html) ?

**Comment by Guria** [comment]
@operatino I really want to participate in `React components library support`. Please keep me in touch.

**Comment by szarouski** [comment]
@Guria that is right :)

**Pull request merged**
