### PR TITLE
SPIKE: ADD languagePlugins for markdown specs

### PR DESCRIPTION
**Pull request by ndelangen**
https://github.com/sourcejs/Source/issues/223 asks for a way to allow spec builders to add pseudo-states documentation to their component.

Right now, a way of doing that is rather verbose and repetitive when added to multiple specs.

We could add more code-blocks / languages to the languageRenderers. But this could potentially grow out of control when supporting many languages?

An other approach I decided to try is to create 'plugins' for markdown codeblock languages. Such plugins would act on code in sequence before the languageRenderers.

The implementation is not finished, I'm hoping this fits #223 use-case. What are your thoughts on this?

### CODE REVIEW

**Comment by custa1200** [comment]
The way I am handling mine atm is:

``` markdown
<% var pseudoClass = [
'',
'pseudo-class-hover',
'pseudo-class-focus',
'pseudo-class-disabled'
] %>

## Radiobutton
Description
<% pseudoClass.forEach(function(pseudoClass){ %>
### <%= pseudoClass %>
Radiobutton <%= pseudoClass %> state.
```example
<div class="input-container--radiobutton">
  <input id="input-radiobutton" class="input input--radiobutton <%= pseudoClass %>" type="radio" name="radiobutton" />
  <label for="input-radiobutton" class="input-label input-label-radiobutton">Radiobutton</label>
</div>
\```
<% }); %>
```

For the following line:
```
### <%= pseudoClass %>
Radiobutton <%= pseudoClass %> state.
```

would be output as:
```
### :link
Radiobutton :link state.
```

**Comment by custa1200** [comment]
Maybe the block could be along the lines of:
``` markdown
``` pseudo:link

```
for pseudo's and somewhere in the plugin settings we can set the class pattern to add so in my case for pseudos I would define ".pseudo-class-*"

Then maybe for states it should be:
``` markdown
``` state:input-error__text--show

```

**Comment by ndelangen** [comment]
@custa1200 

I'm suggesting something that will remove the boilerplate of looping over some array in the spec.
But I'm also trying **not** to introduce tons of addition mutually-exclusive markdown languages.

My proposed end usage would look like this:
```
```example:pseudo
  <a class="button">A default button</a>
​`​`​`
```
which will output:
```
<div class="source-example">
  <div class="pseudo-hover">
    <a class="button">A default button</a>
  </div>
  <div class="pseudo-active">
    <a class="button">A default button</a>
  </div>
  <div class="pseudo-focus">
    <a class="button">A default button</a>
  </div>
  ...
</div>
```

**Comment by custa1200** [comment]
I don't believe that would work in my workflow for a number of reasons. 
The pseudo class should go on the element that has the pseudo not surrounding it. A component could have more than once element within it to demonstrate functionality, i.e a label with an input. Also which Pseudo classes does it add, different elements would have different needs, i.e. a links would be different to inputs.

**Comment by ndelangen** [comment]
> The pseudo class should go on the element that has the pseudo not surrounding it
Can you explain why this is? Why wouldn't a wrapper work too?

**Comment by operatino** [comment]
@ndelangen, I believe @custa1200 wants to have generated spec page with headings and description per each section looped through an array of options (like pseudos).

I still think that EJS templates is the best solution for those kind of custom things, since template could be quite configurable, and act as a plugin either. 

```
<%- include('sourcejs-ejs-templates/pseudos', [pseudos: {'hover', 'active}); %>
``

**Comment by operatino** [comment]
@ndelangen, regarding the extension of code blocks parsing, I like the idea, let's think a bit about namespace syntax. 

Here's an example plugin that was doing similar extension https://github.com/mik01aj/sourcejs-md-react. How do you see the flow in this case? We install the plugin, it exposes some keyword for processing like `jsx` and then user runs it with `example:jsx` code blocks?

If multiple plugins are available, following the order few of them will apply? Kind of like webpack loaders.

Since pseudos looping won't fit this concept, any other ideas of plugins that may extend the examples?

**Comment by ndelangen** [comment]
So I think it'd be great if it would always be like this:

```
​`​`​`{language}:{plugin1},{plugin2}
{code}
​`​`​`
```

`example` is a language, `jsx` is a language.

end then options would go comma-separated after the colon.

```
​`​`​`example:pseudo
{code}
​`​`​`
```

```
​`​`​`jsx:pseudo
{code}
​`​`​`
```

Regarding https://github.com/mik01aj/sourcejs-md-react and the 4 markdown languages it introduces:
```
processMd: {
  languageRenderers: {
    'jsx-init-server': require('sourcejs-md-react/lang-jsx').processServerInit,
    'jsx-init-client': require('sourcejs-md-react/lang-jsx').processClientInit,
    'jsx-component-init-common': require('sourcejs-md-react/lang-jsx').processComponentInit,
    'jsx': require('sourcejs-md-react/lang-jsx').processExample,
  }
}
```

If this at all possible:
May I suggest refactoring this into a single language (jsx) and then create plugins:

```
​`​`​`jsx:jsx-init-server
{code}
​`​`​`
```

Or even have plugin have options:

```
​`​`​`jsx:jsx-init('server')
{code}
​`​`​`
```

This could open up loads of possibilities, but can be quite -let we say- interesting to manage when things come together:

```
​`​`​`jsx:jsx-init('server'),pseudo('active,focus,hover'),fairydust('red')
{code}
​`​`​`
```

**Comment by ndelangen** [comment]
But maybe I'm over-thinking and over-engineering this 🤔

**Comment by operatino** [comment]
>  `jsx:jsx-init('server')`

Hm, options could be a really nice addition, I would go with it from the start, it's not that hard to implement anyways. But of course, the first solution could be done without them.

> `{language}:{plugin1},{plugin2}`

Not sure that we need to group by language. If you'll just provide `jsx` lang, the expected behaviour would be to highlight the jsx code, not to render the example. I would map everything to `example:{...}`, and keep the other langs for just code highlight, which we actually should also allow extending.

**Comment by operatino** [comment]
Hi,

Please ping me when you'll be ready to show first fully working version. As we talked before, switching to markdown-it is a nice idea, although I'm not sure that we should mix many changes in one go.

Most likely this change will go to 0.6.x already.

**Comment by ndelangen** [comment]
Yeah let's plan this this for 0.6.1 or later.
I'll keep working on it, with the switch to markdown-it.

**Comment by Alanoll** [comment]
Instead of using Markdown fences, what using Custom Containers instead?
https://github.com/markdown-it/markdown-it-container

At least for adding support for iterating classes (the class thing is already part of it) and/or for cases were someone wants to add info/doc/warn SourceJS blobs?

**Pull request closed without merging**
