### PR TITLE
Add global dependencies

### PR DESCRIPTION
**Pull request by Realetive**
Add it to local dev. dependencies will be better may be (I don't know).

### CODE REVIEW

**Comment by operatino** [comment]
Hi, 

Actually those dependencies are installed locally, and are not required in global scope to run SourceJS. Could you please share more insight on which problems you had installing the engine?

Grunt is also runnable from npm scripts, without a global dep with `npm run build-source` https://github.com/sourcejs/init/blob/npm/package.json#L6.

**Comment by Realetive** [comment]
```
$ node -v && npm -v
v5.8.0
3.8.1
```
With first try of installation got error (sorry, miss log of it). In error log found information about this packages, that recommended for global installation. After resolve it, error disappeared.

**Comment by operatino** [comment]
I'll check it with this set-up.

**Comment by ndelangen** [comment]
My windows using colleagues have had similar issues, might be relevant to know.

**Comment by operatino** [comment]
I've checked on Mac with Node 5.9.0, that comes with NPM 3.7.3, didn't found this problem, all runs with zero global deps.

@Realetive, could you please define which OS you're on? Windows?

**Comment by operatino** [comment]
I've tested SourceJS installation and start with Windows Node v.5/6 + SourceJS 0.5.6 yo/npm (install options) and 0.6.0 npm. All seems to work perfectly fine without any global modules.

I'll close this for now, if somebody will encounter the same error, please share the npm log on install.

**Pull request closed without merging**
