### PR TITLE
0.6.0 release

### PR DESCRIPTION
**Pull request by ndelangen**
Checklist:

- [x] Change code
- [x] Update documentation
- [ ] Write release notes
- [ ] Migration notes
- [x] Remove old installation flow (based on nested folders)
- [ ] Regression testing (Robert)
- [ ] Re-test all plugins with latest 0.6.0-dev, and deprecate irrelevant ones
- [x] Re-check cross-links in docs (Robert)
- [ ] Add deprecation warnings to features that soon would be deleted  (Robert)
- [ ] Fix issues  #199

- [ ] Re-record an introduction video, showcasing the new installation technique

### CODE REVIEW

**Comment by ndelangen** [comment]
@operatino Anything you need we can help with, to make this happen?

**Comment by operatino** [comment]
- [ ] Remove old installation flow (based on nested folders)
- [ ] Regression testion
- [ ] Re-test all plugins with latest 0.6.0-dev, and deprecate irrelevant ones

**Comment by ndelangen** [comment]
Can you elaborate on what needs to happen for: "Remove old installation flow" ? Can you point to a part of code?

**Comment by Alanoll** [comment]
If we're almost to a point of release, maybe tag a new nightly? NPM install could then be tested.

**Comment by operatino** [comment]
> Can you elaborate on what needs to happen for: "Remove old installation flow" ? Can you point to a part of code?

Until now there's `git clone` installation flow, which assumes nested folders structure. We don't want supporting it anymore. But it's hard to tell now which exactly part of the codebase is responsible for that, at least we can clear the mentions form docs.

> If we're almost to a point of release, maybe tag a new nightly? NPM install could then be tested.

Yes, we should do it, I'll tag it today.

**Comment by ndelangen** [comment]
Didn't I already remove that install flow from the documentation?
I'm not so sure there's much code in core dependent on that flow. Might be a lot of plugin need work though...

**Comment by operatino** [comment]
Released `0.6.0-nightly.7`, starting now validating docs and preping final release.

**Comment by operatino** [comment]
This issue should preferably also be fixed before the release https://github.com/sourcejs/Source/issues/199

**Pull request closed without merging**
