### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ndelangen**
UPDATE dependencies  

I swapped [grunt-casperjs](https://github.com/ronaldlokers/grunt-casperjs) for a [personal (updated) package](https://github.com/ndelangen/grunt-casperjs).
We should swap back when original is updated, but the package hasn't been actively maintained lately.

FIX more restrictive jshint default config by adding exceptions in files that were throwing warnings

### CODE REVIEW

**Comment by ndelangen** [comment]
### Current:
https://gemnasium.com/github.com/sourcejs/Source
screen shot 2016-06-10 at 17 27 50

---

### This PR:
https://gemnasium.com/github.com/ndelangen/sourcejs-Source
screen shot 2016-06-10 at 17 26 24

**Comment by ndelangen** [comment]
I got awfully side-tracked today trying to make npm install smaller & faster 🙂

**Comment by ndelangen** [comment]
The Security alert is for [marked](https://github.com/chjj/marked).

If it's not updated soon we should switch to [markdown-it](https://github.com/markdown-it/markdown-it).
Even if updated, it might be worth switching.

I've swapped marked for markdown-it here:
https://github.com/sourcejs/Source/pull/225/commits/1b548cc93e975c2ecf810542d04fdf571ce3a51f

**Comment by ndelangen** [comment]
Can we have this merged in?

**Comment by operatino** [comment]
Regarding grunt-casperjs, it's fine, we'll replace it with webdriver.io later on. Now looking into changes.

**Pull request merged**
